services:
  - type: web
    name: gestor-emprestimos
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: RELATORIO_DESTINATARIOS
        sync: false
      - key: JOBS_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
